name: CI

on:
    push:
        branches: [ "main", "dev" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: test


        steps:
            - uses: actions/checkout@v3
            - name: Use node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20'
            - run: npm ci
            - run: npm run build